### ISSUE TITLE
create_s3_buckets.py from lesson2 does not work with python 3.6.5

### ISSUE THREAD

**Issue by virtualritz** [cloudshiftstrategies/flask_lambda_lab#1]
https://github.com/cloudshiftstrategies/flask_lambda_lab/blob/lesson2/create_s3_buckets.py does not run with Python 3.6.
There are bunch of errors about ``print`` and missing braces and indexing not being supported.

**Comment by peterb154** [comment]
Thanks! You are correct, it is written to work with python2.x

We can use the
*from __future__ import print_function *

and modify the 9 print statements to use "print*()*" with parentheses
rather than the python 2.x version of print that does not use parentheses.

If you want to make the change and submit a pull request, I'd be happy to
accept the change. Else, I'll get to it sometime in the __future___. (pun)

Thanks.


Brian Peterson

CEO, Cloud Shift Strategies

623-698-8009

www.cloudshiftstrategies.com

<http://www.cloudshiftstrategies.com>

**Comment by virtualritz** [comment]
The print stuff fixed, the next error is
```
Traceback (most recent call last):
  File "./create_s3_buckets.py", line 25, in <module>
    stage=data.keys()[0]
TypeError: 'dict_keys' object does not support indexing
```

I don't know anything about upgrading Python 2.x to 3.x scripts. So I'm just the messenger. No pull request to come from me. :)

**Comment by virtualritz** [comment]
Update: I fixed that using ``stage=list(data.keys())[0]``. But this is not backwards compatible, I guess?
Maybe there should be simply a Python 2 and a Python 3 version of this script?

**Comment by peterb154** [comment]
Ok, I have updated the entire lab to be be python2 and python3 compatible. The issues were around 

1. the python3 print function changed to require parentheses
2. the urllib module changed the way sub-modules (i.e. parse) are imported and 
3. the has_key() and iteritems() methods for lists are no longer available in python3. 

I also updated the [lab instructions](https://www.cloudshiftstrategies.com/flasklambdalab--lesson0.html) lesson0, step 6 to include instructions for using python3 in the lab.
